### ISSUE TITLE
update database.yml structure

### ISSUE THREAD

**Issue by snehithlal** [eventy-core/eventy#8]
- database.yml makes conflicts for different developers so move it into .gitignore
- add bin/setup
- Update reademe

**Comment by snehithlal** [comment]
@ahammednafih  Update README is pending
and why you are not adding Yarn in bin/setup ?

**Comment by ahammednafih** [comment]
> @ahammednafih Update README is pending

Please update readme with any of the issues.
> why you are not adding Yarn in bin/setup ?

Will be fixed with #14 .

**Comment by ahammednafih** [comment]
Database yml structure revamped with #6
